spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: mycloudconfigserver
  cloud:
    config:
      server:
        git:
          uri: ssh://localhost/config-repo
          clone-on-start: true
  security:
    user:
      name: root
      password: s3cr3t

server:
  port: 8888